name: snap-numpy-aaron
base: core18
version: '1.0.0'
summary: numpy and list comprehension snap demo
description: generates a massive list, and uses numpy to remove the evens
grade: stable
confinement: strict

apps:
  snap-numpy-aaron:
    command: bin/snap-numpy-aaron.py

parts:
  snap-numpy-aaron:
    source:
    plugin: python
    python-version: python3
    source-type: git
    python-packages: [numpy]
